image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
# tasks:
# - command: sudo /bin/bash -c '/opt/openhab/start.sh debug' # uncomment if openhab should be started in debug mode at launch

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-preview
  - port: 8081-50000
    onOpen: ignore
  - port: 5007
    onOpen: ignore
  - port: 5005
    onOpen: ignore
